### ISSUE TITLE
Disable DM-Verity

### ISSUE THREAD

**Issue by Massatriof16** [TomKing062/spreadtrum_flash#12]
I'm trying to disable verity on Itel A70 (Unkocked bootloader) but now i got bootloop what happened? Do I need to flash userdata? And What the mean warning : dm-verity need a write-verification-disabled FDL2?

**Comment by TomKing062** [comment]
if you use fdl2-dl, that warning means nothing
when use normal fdl2, flashing will stuck there
for bootloop, i don't really know if itel make any barrier or erase userdata just fine

**Comment by Massatriof16** [comment]
> if you use fdl2-dl, that warning means nothing when use normal fdl2, flashing will stuck there for bootloop, i don't really know if itel make any barrier or erase userdata just fine

Okey i understand but can you fix verity for Itel A70 (sc9863a) It makes bootloop but can be booted if flash original vbmeta but verity Will active again An

**Comment by Massatriof16** [comment]
> if you use fdl2-dl, that warning means nothing when use normal fdl2, flashing will stuck there for bootloop, i don't really know if itel make any barrier or erase userdata just fine

Okey thankyou sir it work using latest version
