### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Massatriof16** [TomKing062/spreadtrum_flash#13]
Sir how can i flash all partition after  using read all

**Comment by Massatriof16** [comment]
> `write_parts folder` (don't try `write_parts .`, i didn't exclude "fdl" files)

can i add blackbox,userdata and cache so it will flash all partition?

**Comment by Massatriof16** [comment]
> `write_parts folder` (don't try `write_parts .`, i didn't exclude "fdl" files)

Sir, I want to ask how to flash a partition or format a partition that is not in the .pac file, for example the hypervsior, l_runtimenv1, common_rs1 and uboot_log partitions

**Comment by TomKing062** [comment]
1 write parts only blacklisted calinv, although on every device it is empty
2 normal `w/write_part` and `e/erase_part`

**Comment by Massatriof16** [comment]
> 1 write parts only blacklisted calinv, although on every device it is empty 2 normal `w/write_part` and `e/erase_part`

so i can ersase ubootlog, erase systemdumpdb for format that? or  just flash the partition file available in the .pac file for flash downgrade or upgrade firmware?

**Comment by TomKing062** [comment]
erase is not equal to format
for format,use partition file or generate (ext4/f2fs) image with tool
ubootlog systemdumpdb are both raw partition,so erase works good

**Comment by Massatriof16** [comment]
> erase is not equal to format for format,use partition file or generate (ext4/f2fs) image with tool ubootlog systemdumpdb are both raw partition,so erase works good

okey so can i  just flash the partition file available in the .pac file for flash downgrade or upgrade firmware?

**Comment by TomKing062** [comment]
yes, just don't touch l_* and nr_*

**Comment by Massatriof16** [comment]
> yes, just don't touch l_* and nr_*

sir can you see whats the problem on itel s25 its already unlock bootloader but every flashing patched boot its always enter bootloader and can't boot , when flash TWRP it will make NO OS and can't boot system. BUT some member can flash it and nothing problem

**Comment by Massatriof16** [comment]
> yes, just don't touch l_* and nr_*

ups sorry sir itel s25 has ROM issue hahah, when flash gsi know can flash magisk.
