### ISSUE TITLE
"write_part" stuck at 97.5%

### ISSUE THREAD

**Issue by RobinNotBad** [TomKing062/spreadtrum_flash#5]
*I'm Chinese and my English may not be very good, I tried my best to describe this issue. : (
Hello, I'm using spd_dump to get root access on a sl8541e(or 9820e) smart watch with Android 8.1. The write_part command can flash vbmeta and logo successfully. But when I tried to flash boot and recovery, the progress stuck at 97.5% and there was no error information. I reboot the device and the 2 partitions didn't change. Is there anything wrong with the signiture, partition size, fdl or something else? 
你好，我正在尝试使用spd_dump在一块sl8541e(或9820e)，Android 8.1的智能手表上获取root权限。“write_part”命令可以正常写入vbmeta和logo。但当我尝试写入boot和recovery时，进度卡在了97.5%并且没有报错信息。我将设备重启，这两个分区并没有被更改。这是因为签名、分区大小、fdl还是其他的错误？
Thanks a lot!

**Comment by TomKing062** [comment]
签名

**Comment by KawaiiSparkle** [comment]
> *I'm Chinese and my English may not be very good, I tried my best to describe this issue. : ( Hello, I'm using spd_dump to get root access on a sl8541e(or 9820e) smart watch with Android 8.1. The write_part command can flash vbmeta and logo successfully. But when I tried to flash boot and recovery, the progress stuck at 97.5% and there was no error information. I reboot the device and the 2 partitions didn't change. Is there anything wrong with the signiture, partition size, fdl or something else? 你好，我正在尝试使用spd_dump在一块sl8541e(或9820e)，Android 8.1的智能手表上获取root权限。“write_part”命令可以正常写入vbmeta和logo。但当我尝试写入boot和recovery时，进度卡在了97.5%并且没有报错信息。我将设备重启，这两个分区并没有被更改。这是因为签名、分区大小、fdl还是其他的错误？ Thanks a lot!

巧了，这个我有办法能刷进去。你能得到分区表对吧，你把partition.xml复制一份，命名为partition_bak.xml，然后修改partition.xml，把里面那个boot和rec的分区名改成其他名称，比如fxxk和wszb，然后保存。在fdl2下应用修改`repartition partition.xml`，这样你就可以往那两个改过名称的分区中刷镜像了（）刷完后，使用`repartition partition_bak.xml`来恢复正常分区名称，然后`reset`下就可以检验成果辣（）
