### ISSUE TITLE
CHECK_BAUD FAIL

### ISSUE THREAD

**Issue by DDZH-DEV** [TomKing062/spreadtrum_flash#6]
![image](https://github.com/user-attachments/assets/295b9cf3-5003-4835-a001-1faab6a57d83)

I've tried all the bitrates（57600,115200,230400,460800,921600,1000000,2000000,3250000,4000000） and it doesn't work, but I can back it up with unlocktool, but unlocktool can't write the partition in, I hope to find a way to solve。

![image](https://github.com/user-attachments/assets/571d574c-f583-4cc8-94f6-69ee427f69c6)

**Comment by TomKing062** [comment]
"CHECK_BAUD FAIL" actually means fail to connect, for fdl1/2 usually is ram initialize failed

about your situation, try fdl from ums512 alldocube

**Comment by DDZH-DEV** [comment]
I've solved it, thank you very much  ，i use the [fdl ](https://www.123pan.com/s/ilffjv-lXR53.html)  and some way write super partition
