### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by CodeGenieMan** [TomKing062/spreadtrum_flash#9]
I have a bricked device (Vortex A24) with an SC9863A chipset. It has an unlocked bootloader, but I don’t have any FDL files for it. I can access BROM mode but not recovery mode. Is there a way to extract the FDL files from the device or flash firmware without them? I also have a second Vortex A24 that isn’t bricked.

**Comment by TomKing062** [comment]
fdl2 is uboot on device, fdl1 can't be extracted from device

what‘s device state, does screen light up or only brom accessible

send your uboot dump,  i can see if it support “SPRD4” mode for flashing
